# Docker Compose Override for Local Development
# This file is automatically loaded and extends docker-compose.yml
# Perfect for developer-specific customizations

version: '3.8'

services:
    app:
        # Enable debugging
        command: ['yarn', 'dev', '--inspect=0.0.0.0:9229']

        # Additional environment variables for development
        environment:
            - DEBUG=*
            - FORCE_COLOR=1
            - TERM=xterm-256color

        # Development-specific volumes
        volumes:
            # Bind mount for better performance on macOS
            - type: bind
              source: .
              target: /app
              consistency: cached

            # Anonymous volumes for better performance
            - /app/node_modules
            - /app/.next
            - /app/coverage

        # Development labels
        labels:
            - 'traefik.enable=true'
            - 'traefik.http.routers.chromezy-dev.rule=Host(`chromezy.local`)'
            - 'traefik.http.services.chromezy-dev.loadbalancer.server.port=3000'
